"""initial schema

Revision ID: 31be2b76e7a2
Revises: 
Create Date: 2026-05-25 22:18:01.117740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31be2b76e7a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ggsel_chats',
    sa.Column('id_i', sa.BigInteger(), nullable=False),
    sa.Column('last_msg_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id_i'),
    schema='marketplace'
    )
    op.create_table('inflight',
    sa.Column('unique_code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('unique_code'),
    schema='marketplace'
    )
    op.create_table('inflight_invoices',
    sa.Column('inv', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('inv'),
    schema='marketplace'
    )
    op.create_table('notified',
    sa.Column('unique_code', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('unique_code', 'kind'),
    schema='marketplace'
    )
    op.create_table('processed_invoices',
    sa.Column('inv', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('inv'),
    schema='marketplace'
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('unique_code', sa.String(), nullable=True),
    sa.Column('inv', sa.BigInteger(), nullable=True),
    sa.Column('goods_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tg_link', sa.String(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('supplier_order_id', sa.String(), nullable=True),
    sa.Column('supplier_status', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='marketplace'
    )
    op.create_index(op.f('ix_marketplace_purchases_created_at'), 'purchases', ['created_at'], unique=False, schema='marketplace')
    op.create_index(op.f('ix_marketplace_purchases_inv'), 'purchases', ['inv'], unique=False, schema='marketplace')
    op.create_index(op.f('ix_marketplace_purchases_platform'), 'purchases', ['platform'], unique=False, schema='marketplace')
    op.create_index(op.f('ix_marketplace_purchases_unique_code'), 'purchases', ['unique_code'], unique=False, schema='marketplace')
    op.create_table('supplier_orders',
    sa.Column('inv', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('inv'),
    schema='marketplace'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_orders', schema='marketplace')
    op.drop_index(op.f('ix_marketplace_purchases_unique_code'), table_name='purchases', schema='marketplace')
    op.drop_index(op.f('ix_marketplace_purchases_platform'), table_name='purchases', schema='marketplace')
    op.drop_index(op.f('ix_marketplace_purchases_inv'), table_name='purchases', schema='marketplace')
    op.drop_index(op.f('ix_marketplace_purchases_created_at'), table_name='purchases', schema='marketplace')
    op.drop_table('purchases', schema='marketplace')
    op.drop_table('processed_invoices', schema='marketplace')
    op.drop_table('notified', schema='marketplace')
    op.drop_table('inflight_invoices', schema='marketplace')
    op.drop_table('inflight', schema='marketplace')
    op.drop_table('ggsel_chats', schema='marketplace')
    # ### end Alembic commands ###
